global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "litestar"
    metrics_path: /metrics
    static_configs:
      - targets: ["accounts_service:8000"]
      - targets: ["catalog_service:8001"]