INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (20, 'Картотеки', 'Шкафы для хранения файлов', 'file_cabinets', 4, null);
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (19, 'Конференц-столы', 'Столы для переговоров', 'conference_tables', 4, 'catalogs/office/conference_tables.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (16, 'Письменные столы', 'Столы для работы', 'desks', 4, 'catalogs/office/desks.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (17, 'Офисные кресла', 'Эргономичные кресла', 'office_chairs', 4, 'catalogs/office/office_chairs.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (18, 'Стеллажи', 'Стеллажи для документов', 'shelves', 4, 'catalogs/office/shelves.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (7, 'Кресла', 'Мягкие кресла для отдыха', 'armchairs', 2, 'catalogs/living_room/armchairs.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (10, 'Книжные шкафы', 'Шкафы для книг и декора', 'bookcases', 2, 'catalogs/living_room/bookcases.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (8, 'Журнальные столики', 'Столики для гостиной', 'coffee_tables', 2, 'catalogs/living_room/coffee_tables.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (6, 'Диваны', 'Удобные диваны и кушетки', 'sofas', 2, 'catalogs/living_room/sofas.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (9, 'ТВ-тумбы', 'Тумбы под телевизор', 'tv_stands', 2, 'catalogs/living_room/tv_stands.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (4, 'Барные стойки', 'Компактные стойки для кухни', 'bar_counters', 1, 'catalogs/kitchen/bar_counters.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (3, 'Кухонные шкафы', 'Шкафы для хранения посуды', 'kitchen_cabinets', 1, 'catalogs/kitchen/kitchen_cabinets.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (2, 'Стулья для кухни', 'Стулья для кухонных столов', 'kitchen_chairs', 1, 'catalogs/kitchen/kitchen_chairs.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (5, 'Табуреты', 'Простые табуреты для кухни', 'kitchen_stools', 1, 'catalogs/kitchen/kitchen_stools.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (1, 'Кухонные столы', 'Столы для обеденной зоны', 'kitchen_tables', 1, 'catalogs/kitchen/kitchen_tables.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (21, 'Детские кровати', 'Кровати для детей', 'kids_beds', 5, 'catalogs/kids_room/kids_beds.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (24, 'Стульчики', 'Детские стулья', 'kids_chairs', 5, 'catalogs/kids_room/kids_chairs.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (25, 'Полки', 'Полки для детских комнат', 'kids_shelves', 5, 'catalogs/kids_room/kids_shelves.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (22, 'Игровые столы', 'Столы для творчества', 'play_tables', 5, 'catalogs/kids_room/play_tables.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (23, 'Шкафы для игрушек', 'Хранение игрушек и одежды', 'toy_cabinets', 5, 'catalogs/kids_room/toy_cabinets.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (11, 'Кровати', 'Комфортные кровати разных размеров', 'beds', 3, 'catalogs/bedroom/beds.png');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (14, 'Комоды', 'Комоды для спальни', 'dressers', 3, 'catalogs/bedroom/dressers.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (15, 'Зеркала', 'Зеркала для спальни', 'mirrors', 3, 'catalogs/bedroom/mirrors.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (13, 'Тумбочки', 'Прикроватные тумбы', 'nightstands', 3, 'catalogs/bedroom/nightstands.jpg');
INSERT INTO public.category (id, name, description, tag, catalog_id, image_path) VALUES (12, 'Шкафы-купе', 'Просторные шкафы для одежды', 'wardrobes', 3, 'catalogs/bedroom/wardrobes.jpg');
