INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (1, 'Стол обеденный круглый', 'round_dining_table', 1, null, 12500.50, 'Круглый стол для семейных обедов, диаметр 120 см');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (2, 'Стол стеклянный', 'glass_table', 1, null, 18900.00, 'Современный стол со стеклянной столешницей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (3, 'Стол раскладной', 'foldable_table', 1, null, 9500.75, 'Компактный раскладной стол для кухни');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (4, 'Деревянный стол', 'wooden_table', 1, null, 15000.00, 'Классический стол из массива дуба');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (5, 'Стул мягкий', 'soft_chair', 2, null, 3500.25, 'Удобный стул с мягкой обивкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (6, 'Стул деревянный', 'wooden_chair', 2, null, 2800.00, 'Простой стул из натурального дерева');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (7, 'Стул металлический', 'metal_chair', 2, null, 3200.50, 'Прочный стул с металлическим каркасом');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (8, 'Стул с подушкой', 'cushioned_chair', 2, null, 4000.00, 'Стул с мягкой подушкой на сиденье');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (9, 'Шкаф угловой', 'corner_cabinet', 3, null, 8700.00, 'Угловой шкаф для экономии пространства');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (10, 'Шкаф навесной', 'wall_cabinet', 3, null, 6500.75, 'Навесной шкаф с двумя полками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (11, 'Шкаф с полками', 'shelf_cabinet', 3, null, 7200.00, 'Шкаф с открытыми полками для посуды');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (12, 'Шкаф белый', 'white_cabinet', 3, null, 9800.50, 'Белый шкаф в современном стиле');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (13, 'Стойка с полкой', 'shelf_bar', 4, null, 14500.00, 'Барная стойка с дополнительной полкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (14, 'Стойка высокая', 'high_bar', 4, null, 16200.25, 'Высокая стойка для стильной кухни');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (15, 'Стойка компактная', 'compact_bar', 4, null, 11000.00, 'Компактная стойка для небольших помещений');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (16, 'Стойка деревянная', 'wooden_bar', 4, null, 13800.50, 'Деревянная стойка с натуральной отделкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (17, 'Табурет круглый', 'round_stool', 5, null, 1800.00, 'Круглый табурет с мягким сиденьем');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (18, 'Табурет высокий', 'tall_stool', 5, null, 2500.75, 'Высокий табурет для барной стойки');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (19, 'Табурет мягкий', 'soft_stool', 5, null, 2200.00, 'Табурет с мягкой обивкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (20, 'Табурет складной', 'foldable_stool', 5, null, 1900.50, 'Складной табурет для удобного хранения');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (21, 'Диван кожаный', 'leather_sofa', 6, null, 45000.00, 'Кожаный диван премиум-класса');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (22, 'Диван угловой', 'corner_sofa', 6, null, 38500.25, 'Угловой диван для гостиной');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (23, 'Диван раскладной', 'foldable_sofa', 6, null, 32000.00, 'Раскладной диван с местом для сна');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (24, 'Диван тканевый', 'fabric_sofa', 6, null, 29500.50, 'Уютный диван с тканевой обивкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (25, 'Кресло мягкое', 'soft_armchair', 7, null, 12500.00, 'Мягкое кресло для отдыха');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (26, 'Кресло качалка', 'rocking_chair', 7, null, 14800.75, 'Кресло-качалка из дерева');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (27, 'Кресло кожаное', 'leather_armchair', 7, null, 18000.00, 'Кожаное кресло с подлокотниками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (28, 'Кресло с подставкой', 'footrest_armchair', 7, null, 19500.50, 'Кресло с выдвижной подставкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (29, 'Столик круглый', 'round_coffee_table', 8, null, 6500.00, 'Круглый столик для гостиной');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (30, 'Столик стеклянный', 'glass_coffee_table', 8, null, 8200.25, 'Стеклянный столик с металлическими ножками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (31, 'Столик с полкой', 'shelf_coffee_table', 8, null, 7000.00, 'Столик с нижней полкой для хранения');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (32, 'Столик деревянный', 'wooden_coffee_table', 8, null, 7800.50, 'Деревянный столик в стиле минимализм');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (33, 'Тумба длинная', 'long_tv_stand', 9, null, 9800.00, 'Длинная тумба под телевизор');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (34, 'Тумба с ящиками', 'drawer_tv_stand', 9, null, 10500.75, 'Тумба с двумя ящиками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (35, 'Тумба белая', 'white_tv_stand', 9, null, 9200.00, 'Белая тумба в скандинавском стиле');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (36, 'Тумба угловая', 'corner_tv_stand', 9, null, 8700.50, 'Угловая тумба для экономии места');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (37, 'Шкаф высокий', 'tall_bookcase', 10, null, 14200.00, 'Высокий шкаф для книг');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (38, 'Шкаф с дверцами', 'door_bookcase', 10, null, 15800.25, 'Шкаф с закрытыми дверцами');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (39, 'Шкаф открытый', 'open_bookcase', 10, null, 11500.00, 'Открытый шкаф для книг и декора');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (40, 'Шкаф узкий', 'narrow_bookcase', 10, null, 9800.50, 'Узкий шкаф для небольших комнат');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (41, 'Кровать Queen-size', 'queen_bed', 11, null, 28500.00, 'Кровать размера Queen с мягким изголовьем');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (42, 'Кровать с ящиками', 'storage_bed', 11, null, 32000.75, 'Кровать с ящиками для хранения');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (43, 'Кровать деревянная', 'wooden_bed', 11, null, 26500.00, 'Кровать из массива дерева');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (44, 'Кровать двухъярусная', 'bunk_bed', 11, null, 19800.50, 'Двухъярусная кровать для детей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (45, 'Шкаф с зеркалом', 'mirror_wardrobe', 12, null, 24500.00, 'Шкаф-купе с зеркальными дверями');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (46, 'Шкаф угловой', 'corner_wardrobe', 12, null, 22800.25, 'Угловой шкаф-купе');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (47, 'Шкаф трехдверный', 'three_door_wardrobe', 12, null, 27500.00, 'Трехдверный шкаф-купе');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (48, 'Шкаф белый', 'white_wardrobe', 12, null, 23500.50, 'Белый шкаф-купе в современном стиле');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (49, 'Тумба с ящиком', 'drawer_nightstand', 13, null, 4500.00, 'Тумбочка с выдвижным ящиком');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (50, 'Тумба круглая', 'round_nightstand', 13, null, 4800.75, 'Круглая тумбочка для спальни');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (51, 'Тумба высокая', 'tall_nightstand', 13, null, 5200.00, 'Высокая тумбочка с полкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (52, 'Тумба деревянная', 'wooden_nightstand', 13, null, 4900.50, 'Деревянная тумбочка в классическом стиле');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (53, 'Комод с зеркалом', 'mirror_dresser', 14, null, 14800.00, 'Комод с зеркалом для спальни');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (54, 'Комод широкий', 'wide_dresser', 14, null, 16500.25, 'Широкий комод с четырьмя ящиками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (55, 'Комод высокий', 'tall_dresser', 14, null, 15200.00, 'Высокий комод для хранения');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (56, 'Комод белый', 'white_dresser', 14, null, 13800.50, 'Белый комод в минималистичном дизайне');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (57, 'Зеркало настенное', 'wall_mirror', 15, null, 3500.00, 'Настенное зеркало в тонкой раме');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (58, 'Зеркало круглое', 'round_mirror', 15, null, 4200.75, 'Круглое зеркало диаметром 80 см');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (59, 'Зеркало с рамой', 'framed_mirror', 15, null, 4800.00, 'Зеркало в деревянной раме');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (60, 'Зеркало большое', 'large_mirror', 15, null, 6500.50, 'Большое напольное зеркало');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (61, 'Стол угловой', 'corner_desk', 16, null, 10500.00, 'Угловой письменный стол');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (62, 'Стол с полками', 'shelf_desk', 16, null, 11800.25, 'Стол с боковыми полками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (63, 'Стол деревянный', 'wooden_desk', 16, null, 9800.00, 'Деревянный стол для работы');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (64, 'Стол компактный', 'compact_desk', 16, null, 8500.50, 'Компактный стол для небольших комнат');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (65, 'Кресло эргономичное', 'ergonomic_chair', 17, null, 14500.00, 'Эргономичное кресло с регулировкой');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (66, 'Кресло с колесами', 'wheeled_chair', 17, null, 12800.75, 'Кресло на колесах для офиса');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (67, 'Кресло кожаное', 'leather_chair', 17, null, 18500.00, 'Кожаное кресло для руководителя');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (68, 'Кресло регулируемое', 'adjustable_chair', 17, null, 15200.50, 'Регулируемое кресло с подлокотниками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (69, 'Стеллаж высокий', 'tall_shelf', 18, null, 9200.00, 'Высокий стеллаж для хранения');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (70, 'Стеллаж открытый', 'open_shelf', 18, null, 7800.25, 'Открытый стеллаж для декора');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (71, 'Стеллаж узкий', 'narrow_shelf', 18, null, 6500.00, 'Узкий стеллаж для компактных помещений');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (72, 'Стеллаж с ящиками', 'drawer_shelf', 18, null, 10500.50, 'Стеллаж с выдвижными ящиками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (73, 'Стол овальный', 'oval_conference_table', 19, null, 24500.00, 'Овальный стол для переговоров');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (74, 'Стол длинный', 'long_conference_table', 19, null, 28500.75, 'Длинный стол на 10 человек');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (75, 'Стол с розетками', 'socket_conference_table', 19, null, 32000.00, 'Стол с встроенными розетками');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (76, 'Стол деревянный', 'wooden_conference_table', 19, null, 26500.50, 'Деревянный стол для офиса');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (77, 'Картотека с замком', 'locked_file_cabinet', 20, null, 9800.00, 'Картотека с замком для документов');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (78, 'Картотека двухсекционная', 'two_section_cabinet', 20, null, 11500.25, 'Двухсекционная картотека');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (79, 'Картотека металлическая', 'metal_file_cabinet', 20, null, 8700.00, 'Металлическая картотека для офиса');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (80, 'Картотека белая', 'white_file_cabinet', 20, null, 9200.50, 'Белая картотека в современном стиле');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (81, 'Кровать с бортиками', 'guarded_kids_bed', 21, null, 12500.00, 'Кровать с бортиками для малышей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (82, 'Кровать двухъярусная', 'kids_bunk_bed', 21, null, 18500.75, 'Двухъярусная кровать для детей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (83, 'Кровать с ящиками', 'storage_kids_bed', 21, null, 14800.00, 'Кровать с ящиками для игрушек');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (84, 'Кровать яркая', 'colorful_kids_bed', 21, null, 13200.50, 'Яркая кровать для детской');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (85, 'Стол для рисования', 'drawing_table', 22, null, 6500.00, 'Стол для детского творчества');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (86, 'Стол с полками', 'shelf_play_table', 22, null, 7800.25, 'Стол с полками для игрушек');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (87, 'Стол круглый', 'round_play_table', 22, null, 6200.00, 'Круглый стол для игр');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (88, 'Стол регулируемый', 'adjustable_play_table', 22, null, 8500.50, 'Регулируемый стол для детей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (89, 'Шкаф с ящиками', 'drawer_toy_cabinet', 23, null, 9200.00, 'Шкаф с ящиками для игрушек');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (90, 'Шкаф яркий', 'colorful_toy_cabinet', 23, null, 8800.25, 'Яркий шкаф для детской');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (91, 'Шкаф открытый', 'open_toy_cabinet', 23, null, 7500.00, 'Открытый шкаф для хранения');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (92, 'Шкаф высокий', 'tall_toy_cabinet', 23, null, 9800.50, 'Высокий шкаф для игрушек');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (93, 'Стул детский мягкий', 'soft_kids_chair', 24, null, 2800.00, 'Мягкий стул для детей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (94, 'Стул высокий', 'tall_kids_chair', 24, null, 3500.75, 'Высокий стул для кормления');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (95, 'Стул деревянный', 'wooden_kids_chair', 24, null, 2500.00, 'Деревянный стул для детской');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (96, 'Стул яркий', 'colorful_kids_chair', 24, null, 3200.50, 'Яркий стул для малышей');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (97, 'Полка настенная', 'wall_kids_shelf', 25, null, 3800.00, 'Настенная полка для детской');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (98, 'Полка с ящиками', 'drawer_kids_shelf', 25, null, 4500.25, 'Полка с ящиками для игрушек');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (99, 'Полка угловая', 'corner_kids_shelf', 25, null, 4200.00, 'Угловая полка для экономии места');
INSERT INTO public.product (id, name, tag, category_id, image_path, price, description) VALUES (100, 'Полка яркая', 'colorful_kids_shelf', 25, null, 4000.50, 'Яркая полка для детской комнаты');
