"""Added image_path

Revision ID: 29be59c2b627
Revises: c014debcf718
Create Date: 2025-04-06 19:28:25.968906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '29be59c2b627'
down_revision: Union[str, None] = 'c014debcf718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog', sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalog', 'image_path')
    # ### end Alembic commands ###
