"""Added cascade delete mode for catalog

Revision ID: 5f2c6b620dfa
Revises: bf7680a86b79
Create Date: 2025-04-20 15:27:51.606577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5f2c6b620dfa'
down_revision: Union[str, None] = 'bf7680a86b79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_catalog_id_fkey', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'catalog', ['catalog_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_catalog_id_fkey', 'category', 'catalog', ['catalog_id'], ['id'])
    # ### end Alembic commands ###
